[package]
name = "ramune"
description = "Packs arbitrary files into a compressed initramfs CPIO archive."
edition.workspace = true
version.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "ramune"
required-features = ["cli"]

[dependencies]
# CLI
clap = { workspace = true, optional = true }

# Compression
zstd = { workspace = true }

# Error handling
anyhow = { workspace = true, optional = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[features]
default = ["cli"]
cli = ["clap", "anyhow"]

[lints]
workspace = true
