[package]
name = "ramune"
description = "Create and extend initramfs images"
edition.workspace = true
version.workspace = true

[[bin]]
name = "ramune"
required-features = ["cli"]

[dependencies]
# Async
tokio = { workspace = true, features = ["fs", "io-util"] }

# CLI
clap = { workspace = true, optional = true }

# Compression
zstd = { workspace = true }

# Error handling
anyhow = { workspace = true, optional = true }
thiserror = { workspace = true }

# Filesystem
erofs = { workspace = true }
tempfile = { workspace = true }

[features]
default = ["cli"]
cli = ["clap", "anyhow"]

[lints]
workspace = true
