[package]
name = "sysconfig"
description = "Configuration management crate for the muak project"
edition.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
toml = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
