[package]
name = "stub"
edition.workspace = true
version.workspace = true

[[bin]]
name = "stub"
path = "src/main.rs"
required-features = ["uefi"]

[dependencies]
# System/platform APIs
uefi = { workspace = true }

# Error handling
anyhow = { workspace = true }

[features]
uefi = []

[lints]
workspace = true
