[package]
name = "imager"
description = "Create initramfs from OCI images"
edition.workspace = true
version.workspace = true

[dependencies]
# CLI parsing
clap = { workspace = true }

# HTTP client
reqwest = { workspace = true, features = ["blocking", "json"] }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# Filesystem utilities
backhand = { workspace = true }
cpio = { workspace = true }
tempfile = { workspace = true }
walkdir = { workspace = true }

# Compression
flate2 = { workspace = true }
tar = { workspace = true }
zstd = { workspace = true }

# Error handling
thiserror = { workspace = true }

[lints]
workspace = true
