[package]
name = "imager"
description = "Create initramfs from OCI images"
edition.workspace = true
version.workspace = true

[[bin]]
name = "imager"
required-features = ["cli"]

[dependencies]
# Async
tokio = { workspace = true, features = ["fs", "io-util"] }
tokio-stream = { workspace = true }

# CLI
clap = { workspace = true, optional = true }

# Compression
flate2 = { workspace = true }
tar = { workspace = true }
zstd = { workspace = true }

# Cryptography
base64ct = { workspace = true }
ring = { workspace = true }

# Encoding
serde = { workspace = true }
serde_json = { workspace = true }

# Error handling
anyhow = { workspace = true, optional = true }
thiserror = { workspace = true }

# Filesystem
backhand = { workspace = true }
walkdir = { workspace = true }
tempfile = { workspace = true }

# HTTP
reqwest = { workspace = true }

[features]
default = ["cli"]
cli = ["clap", "anyhow"]

[lints]
workspace = true
