[package]
name = "init"
edition.workspace = true
version.workspace = true

[dependencies]
# Encoding
base64ct = { workspace = true }

# Error handling
anyhow = { workspace = true }

# Internal
btrfs = { workspace = true }
kmod = { workspace = true }
kmsg = { workspace = true }
luks2 = { workspace = true }

# System/platform APIs
rustix = { workspace = true, features = ["process", "mount", "fs"] }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
