[package]
name = "init"
edition.workspace = true
version.workspace = true

[dependencies]
# System/platform APIs
rustix = { workspace = true, features = ["process"] }

# Error handling
anyhow = { workspace = true }

# Internal
kmod = { path = "../shared/kmod" }
kmsg = { path = "../shared/kmsg" }

[lints]
workspace = true
