#!/bin/busybox sh

rescue_shell() {
    echo "!!! Something went wrong. Dropping to rescue shell."
    echo "!!! Exit the shell to continue booting (if possible)."
    exec /bin/busybox sh
}

cmdline() {
    local value
    value=" $(cat /proc/cmdline) "
    value="${value##* ${1}=}"
    value="${value%% *}"
    [ "${value}" != "" ] && echo "${value}"
}

break_requested() {
    local want_break
    for o in $(cat /proc/cmdline) ; do
        case "$o" in
            rd.break|rdbreak) want_break="yes" ;;
            init=/bin/sh|init=/bin/bb|init=/bin/bash) want_break="yes" ;;
        esac
    done
    echo "${want_break}"
}

echo "==== Muak initramfs ===="
echo "Starting dinit as init..."

exec /sbin/dinit
