[package]
name = "erofs"
description = "A Rust library for working with EROFS (Enhanced Read-Only File System)."
edition.workspace = true
version.workspace = true

[dependencies]
# Error handling
thiserror = { workspace = true }

# Filesystem
crc32c = { workspace = true }
walkdir = { workspace = true }

# Utilities
uuid = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
