[package]
name = "tpm2"
description = "Library to interact with TPM2 devices"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# Cryptography
getrandom = { workspace = true }
sha2 = { workspace = true }
zeroize = { workspace = true }

# Error handling
thiserror = { workspace = true }

[lints]
workspace = true
