[package]
name = "provisiond"
edition.workspace = true
version.workspace = true

[dependencies]
# Asynchronous
tokio = { workspace = true, features = ["fs"] }
tokio-stream = { workspace = true }

# Encoding
base64ct = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
prost = { workspace = true }

# Cryptography
ring = { workspace = true }
x509-cert = { workspace = true }
uuid = { workspace = true, features = ["v4", "v7"] }

# Error handling
anyhow = { workspace = true }

# Filesystem
gptman = { workspace = true }
fatfs = { workspace = true }

# gRPC
tonic = { workspace = true }
tonic-prost = { workspace = true }

# Internal
btrfs = { workspace = true }
imager = { workspace = true }
kmsg = { workspace = true }
luks2 = { workspace = true }
notify = { workspace = true }
pki = { workspace = true }
sysconfig = { workspace = true }
sbolt = { workspace = true }
yuki = { workspace = true }

# System/platform APIs
rustix = { workspace = true, features = ["process", "system", "net", "mount", "fs"] }
libc = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }

[lints]
workspace = true
