[package]
name = "granola"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.29", features = ["signal", "process"] }
tokio = { version = "1", features = ["rt-multi-thread", "net", "sync", "macros", "time"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.12"
prost = "0.13"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
rtnetlink = "0.14"
futures = "0.3"
dhcproto = "0.12"
rand = "0.8"
netlink-packet-route = "0.19"
libc = "0.2"

[build-dependencies]
tonic-build = "0.12"

[profile.release]
opt-level = "z"
lto = true
strip = true
panic = "abort"
codegen-units = 1
