[package]
name = "timed"
description = "NTP time synchronization daemon"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# Internal crates
granola = { workspace = true }
config = { workspace = true }

# Async runtime
tokio = { workspace = true, features = ["rt", "macros", "net", "time", "signal"] }

# System APIs
rustix = { workspace = true, features = ["time"] }

# Error handling
anyhow = { workspace = true }

[lints]
workspace = true
