[package]
name = "apid"
edition.workspace = true
version.workspace = true

[dependencies]
# Asynchronous
tokio = { workspace = true, features = ["net", "sync", "time", "signal", "fs", "io-util"] }
tokio-rustls = { workspace = true }

# Cryptography
x509-cert = { workspace = true }
ring = { workspace = true }
rustls = { workspace = true }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# HTTP
hyper = { workspace = true }
hyper-util = { workspace = true }
http-body-util = { workspace = true }

# Internal
granola = { workspace = true }
kmsg = { workspace = true }
pki = { workspace = true }
config = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
