[package]
name = "muak"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true, features = ["macros", "io-util", "fs"] }
tokio-stream = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
clap = { workspace = true }
tower = { workspace = true }
chrono = { workspace = true }
hyper-util = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
