[package]
name = "muak"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "io-util"] }
tonic = "0.12"
prost = "0.13"
clap = { version = "4", features = ["derive"] }
tower = "0.4"
chrono = "0.4"
hyper-util = { version = "0.1", features = ["tokio"] }

[build-dependencies]
tonic-build = "0.12"

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
