[package]
name = "muakctl"
description = "Muak command line interface"
edition.workspace = true
version.workspace = true

[dependencies]
# Asynchronous
tokio = { workspace = true, features = ["macros", "io-util", "fs"] }
tokio-stream = { workspace = true }
tokio-rustls = { workspace = true }

# CLI
clap = { workspace = true, features = ["env"] }
owo-colors = { workspace = true }

# Cryptography
rustls = { workspace = true }

# Encoding
base64ct = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }

# Error handling
anyhow = { workspace = true }

# gRPC
tonic = { workspace = true }
tonic-prost = { workspace = true }

# HTTP
hyper = { workspace = true }
hyper-util = { workspace = true }

# Internal
pki = { workspace = true }
sysconfig = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }

[lints]
workspace = true
