[package]
name = "parttable"
description = "Shared MBR and GPT partition table helpers"
edition.workspace = true
version.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# Compression
gptman = { workspace = true }

# Error handling
thiserror = { workspace = true }

# Filesyste
crc32fast = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
