[package]
name = "parttable"
description = "Parsing and manipulating GPT & MBR partition tables"
edition.workspace = true
version.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# Error handling
thiserror = { workspace = true }

# Filesystem
crc32fast = { workspace = true }

[dev-dependencies]
esp = { workspace = true }

[lints]
workspace = true
