[package]
name = "mumi"
description = "Seals a directory into a compressed immutable image"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "mumi"
required-features = ["cli"]

[dependencies]
# CLI
clap = { workspace = true, optional = true }

# Error handling
anyhow = { workspace = true, optional = true }
thiserror = { workspace = true }

# Internal
erofs = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[features]
default = ["cli"]
cli = ["clap", "anyhow"]

[lints]
workspace = true
