[package]
name = "yuki"
description = "A tool for working with UKIs"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# Cryptography
sha2 = { workspace = true }

# Error handling
thiserror = { workspace = true }

# Internal
uki = { workspace = true }

# Utilities
object = { workspace = true }

[lints]
workspace = true
