[package]
name = "granola"
edition.workspace = true
version.workspace = true

[dependencies]
# Asynchronous
tokio = { workspace = true, features = ["signal"] }
tokio-stream = { workspace = true }

# Encoding
prost = { workspace = true }

# Error handling
anyhow = { workspace = true }

# gRPC
tonic = { workspace = true }
tonic-prost = { workspace = true }

# System/platform APIs
rustix = { workspace = true, features = ["process"] }

# Internal
kmsg = { workspace = true }
sysconfig = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }

[lints]
workspace = true
