[package]
name = "e2e"
description = "End-to-end tests for Muak (requires QEMU)"
edition.workspace = true
version.workspace = true

[dependencies]
# Asynchronous
tokio = { workspace = true, features = ["process", "net", "time", "io-util"] }

# Encoding
toml = { workspace = true }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Filesystem
tempfile = { workspace = true }

[lints]
workspace = true
