[package]
name = "e2e"
description = "End-to-end tests for Muak (requires QEMU)"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# Asynchronous
tokio = { workspace = true, features = ["process", "net", "time", "io-util"] }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Filesystem
tempfile = { workspace = true }

# Internal
config = { workspace = true }

[lints]
workspace = true
