[package]
name = "stub"
description = "EFI stub binary and library"
edition.workspace = true
version.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "stub"
path = "src/lib.rs"

[[bin]]
name = "stub"
path = "src/main.rs"
required-features = ["uefi"]

[dependencies]
# Error handling
anyhow = { workspace = true }

# System/platform APIs
uefi = { workspace = true }

# Encoding
base64ct = { workspace = true }

# Utilities
object = { workspace = true }

[features]
uefi = []

[lints]
workspace = true
