[package]
name = "pki"
description = "PKI and certificate utilities"
edition.workspace = true
version.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# Cryptography
x509-cert = { workspace = true }
der = { workspace = true }
spki = { workspace = true }
const-oid = { workspace = true }
ring = { workspace = true }
signature = { workspace = true }
zeroize = { workspace = true }

# Error handling
thiserror = { workspace = true }

[lints]
workspace = true
