[package]
name = "networkd"
edition.workspace = true
version.workspace = true

[dependencies]
# Asynchronous
tokio = { workspace = true, features = ["net", "sync", "time", "signal", "fs", "io-util"] }
tokio-stream = { workspace = true }
tokio-rustls = { workspace = true }

# Cryptography
ring = { workspace = true }
rustls = { workspace = true }
rustls-pki-types = { workspace = true }
webpki-roots = { workspace = true }

# Encoding
prost = { workspace = true }

# Error handling
anyhow = { workspace = true }

# gRPC
tonic = { workspace = true }
tonic-prost = { workspace = true }

# HTTP
hyper = { workspace = true }
hyper-util = { workspace = true }
hyper-rustls = { workspace = true }
http-body-util = { workspace = true }

# Internal
kmsg = { workspace = true }
notify = { workspace = true }
config = { workspace = true }

# Networking
rtnetlink = { workspace = true }

# System/platform APIs
rustix = { workspace = true, features = ["net", "event", "time"] }
libc = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }

[lints]
workspace = true
