[package]
name = "networkd"
description = "Network configuration and management daemon"
edition.workspace = true
version.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# Asynchronous
tokio = { workspace = true, features = ["net", "sync", "time", "signal", "fs", "io-util"] }

# Error handling
anyhow = { workspace = true }

# Internal
granola = { workspace = true }
kmsg = { workspace = true }
config = { workspace = true }
netlib = { workspace = true }

# Networking
rtnetlink = { workspace = true }

# Cryptography
ring = { workspace = true }

# System/platform APIs
rustix = { workspace = true, features = ["net", "event", "time"] }
libc = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
tempfile = { workspace = true }
