[package]
name = "networkd"
edition.workspace = true
version.workspace = true

[dependencies]
# Asynchronous
tokio = { workspace = true, features = ["net", "sync", "time", "signal", "fs", "io-util"] }
tokio-stream = { workspace = true }

# Encoding
prost = { workspace = true }

# Error handling
anyhow = { workspace = true }

# gRPC
tonic = { workspace = true }
tonic-prost = { workspace = true }

# Internal
granola = { workspace = true }
kmsg = { workspace = true }
config = { workspace = true }
netlib = { workspace = true }

# Networking
rtnetlink = { workspace = true }

# System/platform APIs
rustix = { workspace = true, features = ["net", "event", "time"] }
libc = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
protox = { workspace = true }

[lints]
workspace = true
