[package]
name = "yuki"
description = "UKI builder - add PE sections to EFI stub"
edition.workspace = true
version.workspace = true

[dependencies]
# CLI
clap = { workspace = true }

# Error handling
thiserror = { workspace = true }

# Utilities
object = { workspace = true }

[lints]
workspace = true
