[package]
name = "yuki"
version = "0.1.0"
description = "UKI builder - add PE sections to EFI stub"
edition.workspace = true

[dependencies]
# CLI parsing
clap = { workspace = true }

# Utilities
object = { workspace = true }

# Error handling
anyhow = { workspace = true }

[lints]
workspace = true
