[package]
name = "modd"
edition.workspace = true
version.workspace = true

[dependencies]
# Compression
zstd = { workspace = true }

# Error handling
anyhow = { workspace = true }

# Internal
kmod = { workspace = true }
kmsg = { workspace = true }
notify = { workspace = true }

# System/platform APIs
rustix = { workspace = true, features = ["net", "system"] }

[lints]
workspace = true
