[package]
name = "modd"
edition.workspace = true
version.workspace = true

[dependencies]
# Compression
zstd = { workspace = true }

# Error handling
anyhow = { workspace = true }

# Internal
kmod = { path = "../shared/kmod" }
kmsg = { path = "../shared/kmsg" }
notify = { path = "../shared/notify" }

# System/platform APIs
rustix = { workspace = true, features = ["net", "system"] }

[lints]
workspace = true
