[package]
name = "config"
description = "Configuration management crate for the muak project"
edition.workspace = true
version.workspace = true

[dependencies]
# Encoding
base64ct = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
