[package]
name = "kmod"
edition.workspace = true
version.workspace = true

[dependencies]
# System/platform APIs
rustix = { workspace = true, features = ["system"] }

# Compression
zstd = { workspace = true }

# Error handling
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
