[package]
name = "networkd"
edition.workspace = true
version.workspace = true

[dependencies]
# Asynchronous
tokio = { workspace = true, features = ["net", "sync", "macros", "time", "signal", "fs", "io-util", "rt-multi-thread"] }
tokio-stream = { workspace = true }

# Compression
ring = { workspace = true }

# Encoding
serde = { workspace = true }
prost = { workspace = true }

# Error handling
anyhow = { workspace = true }

# gRPC
tonic = { workspace = true }
tonic-prost = { workspace = true }

# HTTP
reqwest = { workspace = true }
hyper-util = { workspace = true }

# Internal
kmsg = { workspace = true }
notify = { workspace = true }
sysconfig = { workspace = true }

# Networking
rtnetlink = { workspace = true }
netlink-packet-route = { workspace = true }
netlink-packet-core = { workspace = true }
tower = { workspace = true }

# System/platform APIs
rustix = { workspace = true, features = ["net", "event", "time"] }
libc = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }

[lints]
workspace = true
