[package]
name = "vmd"
description = "Virtual machine management daemon"
edition.workspace = true
version.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# Asynchronous
tokio = { workspace = true, features = ["net", "sync", "time", "signal", "fs", "io-util", "process"] }
tokio-stream = { workspace = true }

# Encoding
serde = { workspace = true }
serde_json = { workspace = true }
prost = { workspace = true }

# Error handling
anyhow = { workspace = true }

# gRPC
tonic = { workspace = true }
tonic-prost = { workspace = true }

# Internal
btrfs = { workspace = true }
config = { workspace = true }
granola = { workspace = true }
kmsg = { workspace = true }
netlib = { workspace = true }

# Networking
rtnetlink = { workspace = true }

# System/platform APIs
rustix = { workspace = true, features = ["process"] }
libc = { workspace = true }

# Utilities
uuid = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
protox = { workspace = true }

[lints]
workspace = true
