[package]
name = "modd"
description = "Kernel module management daemon"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# Error handling
anyhow = { workspace = true }

# Internal
granola = { workspace = true }
kmod = { workspace = true }

# System/platform APIs
rustix = { workspace = true, features = ["net", "system"] }

[lints]
workspace = true
