[package]
name = "apid"
edition.workspace = true
version.workspace = true

[dependencies]
# Core async runtime
tokio = { workspace = true, features = ["net", "sync", "macros", "time", "signal", "fs", "io-util", "rt-multi-thread"] }

# HTTP/2 proxy
hyper = { workspace = true }
hyper-util = { workspace = true }
http-body-util = { workspace = true }

# Utilities
anyhow = { workspace = true }

# Internal
kmsg = { path = "../shared/kmsg" }
notify = { path = "../shared/notify" }
sysconfig = { path = "../shared/sysconfig" }

[lints]
workspace = true
