[package]
name = "imager"
description = "Pull and sign OCI images"
edition.workspace = true
version.workspace = true

[[bin]]
name = "imager"
required-features = ["cli"]

[dependencies]
# Async
tokio = { workspace = true, features = ["fs", "io-util"] }
tokio-stream = { workspace = true }
tokio-rustls = { workspace = true }

# CLI
clap = { workspace = true, optional = true }

# Compression
flate2 = { workspace = true }
tar = { workspace = true }

# Cryptography
ring = { workspace = true }
rustls = { workspace = true }
webpki-roots = { workspace = true }

# Encoding
serde = { workspace = true }
serde_json = { workspace = true }
base64ct = { workspace = true }

# Error handling
anyhow = { workspace = true, optional = true }
thiserror = { workspace = true }

# HTTP
hyper = { workspace = true }
hyper-util = { workspace = true }
hyper-rustls = { workspace = true }
http-body-util = { workspace = true }

[features]
default = ["cli"]
cli = ["clap", "anyhow"]

[lints]
workspace = true
