[package]
name = "kmsg"
description = "Kernel message logging utilities"
edition.workspace = true
version.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# Error handling
thiserror = { workspace = true }

# System/platform APIs
rustix = { workspace = true }

[features]
default = []
debug = []

[lints]
workspace = true
