# Muak System Configuration
#
# This is the default configuration template.
# Generate a copy with: muakctl config generate > config.toml
# Install with:         muakctl install --endpoint <ip>:50051 --config config.toml --insecure

[host]
name = "muak"
image = "ghcr.io/muak-os/installer:latest"
extensions = []
secureboot = true
port = 50051
ntp = "pool.ntp.org"

[disk]
system = ""
# data = ""

[network]
ipv6 = true

[vm]
auto_restart = true
