[package]
name = "init"
description = "Muak init process"
edition.workspace = true
version.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# Cryptography
zeroize = { workspace = true }

# Encoding
base64ct = { workspace = true }

# Error handling
anyhow = { workspace = true }

# Internal
btrfs = { workspace = true }
kmod = { workspace = true }
kmsg = { workspace = true }
luks2 = { workspace = true }
tpm2 = { workspace = true }

# System/platform APIs
rustix = { workspace = true, features = ["process"] }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
