[package]
name = "btrfs"
description = "Btrfs filesystem helpers"
edition.workspace = true
version.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# Error handling
thiserror = { workspace = true }

# Filesystem
crc32c = { workspace = true }

# System/platform APIs
rustix = { workspace = true }

# Utilities
uuid = { workspace = true }

[lints]
workspace = true
