[package]
name = "oci"
description = "Open Container Initiative specification"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# Cryptography
sha2 = { workspace = true }

# Encoding
base16ct = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

# Error handling
thiserror = { workspace = true }

[lints]
workspace = true
