[package]
name = "wizard"
description = "Deterministic image build pipeline"
edition.workspace = true
version.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "wizard"
required-features = ["cli"]

[dependencies]
# Compression
tar = { workspace = true }

# Cryptography
ring = { workspace = true }

# CLI
clap = { workspace = true, optional = true }

# Encoding
serde = { workspace = true }
toml = { workspace = true }

# Error handling
anyhow = { workspace = true, optional = true }
thiserror = { workspace = true }

# Internal
mumi = { workspace = true, default-features = false }
esp = { workspace = true }
koci = { workspace = true, default-features = false }
miso = { workspace = true, default-features = false }
ramune = { workspace = true, default-features = false }
sbolt = { workspace = true }
yuki = { workspace = true, default-features = false }

[features]
default = ["cli"]
cli = ["anyhow", "clap"]

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
