name: Build CLI

on:
  push:
    branches: [master]
    paths:
      - "cli/**"
      - "libs/pki/**"
      - "libs/config/**"
      - "api/*.proto"
    tags:
      - "v[0-9]+.*"
  pull_request:
    paths:
      - "cli/**"
      - "libs/pki/**"
      - "libs/config/**"
      - "api/*.proto"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_template.yaml
    with:
      image: muakctl
      recipe: oci cli
      push: ${{ github.event_name != 'pull_request' }}
      latest: ${{ startsWith(github.ref, 'refs/tags/') }}

