name: Build Tools

on:
  push:
    branches: [master]
    paths:
      - "tools/miso/**"
      - "tools/koci/**"
      - "tools/ramune/**"
      - "tools/yuki/**"
      - "libs/erofs/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "Justfile"
      - "rust-toolchain.toml"
      - ".dockerignore"
    tags:
      - "v[0-9]+.*"
  pull_request:
    paths:
      - "tools/miso/**"
      - "tools/koci/**"
      - "tools/ramune/**"
      - "tools/yuki/**"
      - "libs/erofs/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "Justfile"
      - "rust-toolchain.toml"
      - ".dockerignore"
  workflow_dispatch:
    inputs:
      latest:
        description: "Tag the image as latest"
        required: false
        type: boolean
        default: true
      tag:
        description: "Tag to build (defaults to current commit)"
        required: false
        type: string

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_template.yaml
    with:
      image: tools
      recipe: oci tools
      push: ${{ github.event_name != 'pull_request' }}
      latest: ${{ startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && inputs.latest) }}
      tag: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || '' }}
      arch_matrix: '["amd64"]'
