name: Build Installer

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build (defaults to current commit)"
        required: false
        type: string

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_template.yaml
    with:
      image: installer
      recipe: oci installer
      push: true
      latest: true
      tag: ${{ inputs.tag }}
      sign: true
    secrets:
      COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
