name: Build Kernel

on:
  push:
    tags:
      - "v[0-9]+.*"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_template.yaml
    with:
      image: kernel
      recipe: kernel
      push: true
      latest: ${{ startsWith(github.ref, 'refs/tags/') }}
      free_disk_space: true
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      KERNEL_SIGNING_KEY: ${{ secrets.KERNEL_SIGNING_KEY }}
