[package]
name = "koci"
description = "OCI images management tool"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "koci"
required-features = ["cli"]

[dependencies]
# Async
tokio = { workspace = true, features = ["fs", "io-util"] }

# CLI
clap = { workspace = true, optional = true }

# Compression
flate2 = { workspace = true }
tar = { workspace = true }

# Cryptography
getrandom = { workspace = true }
p256 = { workspace = true }
sha2 = { workspace = true }
signature = { workspace = true }
rustls = { workspace = true }
webpki-roots = { workspace = true }

# Encoding
serde = { workspace = true }
serde_json = { workspace = true }
base16ct = { workspace = true }
base64ct = { workspace = true }

# Error handling
anyhow = { workspace = true, optional = true }
thiserror = { workspace = true }

# HTTP
hyper = { workspace = true }
hyper-util = { workspace = true }
hyper-rustls = { workspace = true }
http-body-util = { workspace = true }

[features]
default = ["cli"]
cli = ["clap", "anyhow"]

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
