[package]
name = "koci"
description = "OCI images management tool"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "koci"
required-features = ["cli"]

[dependencies]
# Asynchronous
tokio = { workspace = true, features = ["fs", "io-util"] }

# CLI
clap = { workspace = true, optional = true }

# Compression
flate2 = { workspace = true }
tar = { workspace = true }

# Cryptography
base64ct = { workspace = true }
p256 = { workspace = true }
signature = { workspace = true }

# Encoding
serde_json = { workspace = true }

# Error handling
anyhow = { workspace = true, optional = true }
thiserror = { workspace = true }

# Internal
oci = { workspace = true }
oci-client = { workspace = true }

# Utilities
bytes = { workspace = true }

[features]
default = ["cli"]
cli = ["clap", "anyhow"]

[dev-dependencies]
getrandom = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
